# db/seeds/ingredients.rb
# Bulk load of Argentine ingredients
puts "Loading Argentine ingredients..."

INGREDIENTS = {
  "Carnes vacunas" => [
    { name: "Bife de chorizo", aliases: "bife, churrasquito" },
    { name: "Bife de costilla", aliases: "t-bone" },
    { name: "Bife ancho", aliases: "ojo de bife, rib eye" },
    { name: "Bife angosto", aliases: "striploin" },
    { name: "Entraña", aliases: "skirt steak" },
    { name: "Vacío", aliases: "vacio, flank" },
    { name: "Matambre de vaca", aliases: "matambre, matambre vacuno" },
    { name: "Asado de tira", aliases: "tira de asado, costilla" },
    { name: "Tapa de asado", aliases: "tapa" },
    { name: "Cuadril", aliases: "rump steak" },
    { name: "Lomo de vaca", aliases: "lomo, solomillo, tenderloin" },
    { name: "Peceto", aliases: "eye of round" },
    { name: "Nalga", aliases: "nalga de ternera" },
    { name: "Bola de lomo", aliases: "bola" },
    { name: "Paleta de vaca", aliases: "paleta, chuck" },
    { name: "Carnaza", aliases: "carnaza negra" },
    { name: "Carnaza cuadrada", aliases: nil },
    { name: "Garrón", aliases: "osobuco con hueso, jarrete" },
    { name: "Osobuco", aliases: "osso buco" },
    { name: "Falda", aliases: "falda de vaca" },
    { name: "Aguja", aliases: "aguja de vaca" },
    { name: "Palomita", aliases: "palomita de vaca" },
    { name: "Tortuguita", aliases: nil },
    { name: "Colita de cuadril", aliases: "colita" },
    { name: "Marucha", aliases: nil },
    { name: "Tapa de nalga", aliases: nil },
    { name: "Carne picada común", aliases: "carne picada, carne molida" },
    { name: "Carne picada especial", aliases: "carne picada magra" },
    { name: "Carne para guiso", aliases: "carne cortada en cubos" },
    { name: "Carne para milanesa", aliases: "milanesa de carne, milanesas" },
    { name: "Carne para estofado", aliases: nil },
    { name: "Roast beef", aliases: "rosbif" },
    { name: "Cuadrada", aliases: "cuadrada de vaca" },
    { name: "Peceto mechado", aliases: nil },
    { name: "Ternera", aliases: "carne de ternera" },
    { name: "Costillar de vaca", aliases: "costillar" },
    { name: "Pecho de vaca", aliases: "pecho" },
    { name: "Cogote", aliases: "cogote de vaca" },
    { name: "Hueso con caracú", aliases: "caracú, hueso con tuétano" },
    { name: "Medallón de lomo", aliases: nil },
    { name: "Hamburguesa de carne", aliases: "hamburguesa casera" },
    { name: "Milanesa de nalga", aliases: nil },
    { name: "Milanesa de peceto", aliases: nil },
    { name: "Milanesa de cuadrada", aliases: nil },
    { name: "Bife de lomo", aliases: nil },
    { name: "Cima rellena", aliases: "cima" },
    { name: "Churrasco", aliases: "churrasco de cuadril" },
  ],

  "Carnes de cerdo" => [
    { name: "Bondiola de cerdo", aliases: "bondiola" },
    { name: "Carré de cerdo", aliases: "carre, lomo de cerdo" },
    { name: "Costeleta de cerdo", aliases: "costilla de cerdo, chuleta" },
    { name: "Pechito de cerdo", aliases: "costillitas, spare ribs" },
    { name: "Matambre de cerdo", aliases: nil },
    { name: "Solomillo de cerdo", aliases: "lomo fino de cerdo" },
    { name: "Jamón de cerdo fresco", aliases: "pierna de cerdo" },
    { name: "Panceta fresca", aliases: "belly, panza de cerdo" },
    { name: "Panceta ahumada", aliases: "bacon" },
    { name: "Tocino", aliases: nil },
    { name: "Chicharrón", aliases: "chicharrones" },
    { name: "Codillo de cerdo", aliases: nil },
    { name: "Patita de cerdo", aliases: "pata de cerdo" },
    { name: "Punta de espalda", aliases: nil },
    { name: "Paleta de cerdo", aliases: nil },
    { name: "Milanesa de cerdo", aliases: nil },
    { name: "Carne picada de cerdo", aliases: nil },
    { name: "Lechón", aliases: "lechón entero, cochinillo" },
    { name: "Hamburguesa de cerdo", aliases: nil },
    { name: "Costillar de cerdo", aliases: nil },
    { name: "Osobuco de cerdo", aliases: nil },
    { name: "Seco de cerdo", aliases: nil },
    { name: "Paleta de cerdo deshuesada", aliases: nil },
    { name: "Cuero de cerdo", aliases: nil },
    { name: "Grasa de cerdo", aliases: "grasa de pella" },
    { name: "Manteca de cerdo", aliases: nil },
  ],

  "Aves" => [
    { name: "Pollo entero", aliases: "pollo" },
    { name: "Pechuga de pollo", aliases: "pechuga, suprema sin hueso" },
    { name: "Suprema de pollo", aliases: "suprema" },
    { name: "Muslo de pollo", aliases: "muslo" },
    { name: "Pata muslo de pollo", aliases: "pata muslo, pata entera" },
    { name: "Pata de pollo", aliases: "pata" },
    { name: "Ala de pollo", aliases: "alita, alita de pollo" },
    { name: "Pollo trozado", aliases: "pollo en presas" },
    { name: "Menudos de pollo", aliases: "menudos" },
    { name: "Hígado de pollo", aliases: nil },
    { name: "Corazón de pollo", aliases: nil },
    { name: "Molleja de pollo", aliases: nil },
    { name: "Carcasa de pollo", aliases: "huesos de pollo" },
    { name: "Pollo deshuesado", aliases: nil },
    { name: "Milanesa de pollo", aliases: nil },
    { name: "Carne picada de pollo", aliases: nil },
    { name: "Pavo entero", aliases: "pavo" },
    { name: "Pechuga de pavo", aliases: nil },
    { name: "Muslo de pavo", aliases: nil },
    { name: "Gallina", aliases: "gallina para caldo" },
    { name: "Codorniz", aliases: "codornices" },
    { name: "Pato", aliases: "pato entero" },
    { name: "Pechuga de pato", aliases: nil },
    { name: "Confit de pato", aliases: nil },
    { name: "Faisán", aliases: nil },
    { name: "Pintada", aliases: "guinea fowl" },
    { name: "Hamburguesa de pollo", aliases: nil },
    { name: "Nuggets de pollo", aliases: nil },
  ],

  "Pescados y mariscos" => [
    { name: "Merluza", aliases: "merluza común, filet de merluza" },
    { name: "Merluza negra", aliases: nil },
    { name: "Surubí", aliases: "surubi" },
    { name: "Dorado", aliases: nil },
    { name: "Pejerrey", aliases: nil },
    { name: "Trucha", aliases: "trucha arcoíris" },
    { name: "Salmón fresco", aliases: "salmón, salmon" },
    { name: "Salmón ahumado", aliases: nil },
    { name: "Atún fresco", aliases: nil },
    { name: "Atún en lata", aliases: "atún enlatado" },
    { name: "Lenguado", aliases: nil },
    { name: "Corvina", aliases: nil },
    { name: "Brótola", aliases: nil },
    { name: "Abadejo", aliases: nil },
    { name: "Mero", aliases: nil },
    { name: "Pacú", aliases: "pacu" },
    { name: "Boga", aliases: nil },
    { name: "Sábalo", aliases: nil },
    { name: "Caballa", aliases: nil },
    { name: "Caballa en lata", aliases: nil },
    { name: "Sardina fresca", aliases: nil },
    { name: "Sardinas en lata", aliases: "sardinas enlatadas" },
    { name: "Anchoa", aliases: "anchoas, boquerón" },
    { name: "Bacalao", aliases: "bacalao seco, bacalao desalado" },
    { name: "Besugo", aliases: nil },
    { name: "Chernia", aliases: nil },
    { name: "Pez espada", aliases: nil },
    { name: "Calamar", aliases: "calamares, calamarete" },
    { name: "Calamar limpio", aliases: "tubos de calamar" },
    { name: "Pulpo", aliases: nil },
    { name: "Mejillones", aliases: "mejillón" },
    { name: "Mejillones en conserva", aliases: nil },
    { name: "Langostinos", aliases: "langostino" },
    { name: "Camarones", aliases: "camarón" },
    { name: "Gambas", aliases: nil },
    { name: "Vieiras", aliases: "vieira" },
    { name: "Almejas", aliases: "almeja" },
    { name: "Berberechos", aliases: nil },
    { name: "Centolla", aliases: nil },
    { name: "Cangrejo", aliases: nil },
    { name: "Surimi", aliases: "kanikama, palitos de cangrejo" },
    { name: "Rabas", aliases: nil },
    { name: "Cornalitos", aliases: nil },
  ],

  "Achuras y menudencias" => [
    { name: "Mollejas", aliases: "molleja" },
    { name: "Chinchulines", aliases: "chinchulin, chinchulín" },
    { name: "Riñones de vaca", aliases: "riñón" },
    { name: "Hígado de vaca", aliases: "hígado" },
    { name: "Corazón de vaca", aliases: "corazón" },
    { name: "Lengua de vaca", aliases: "lengua" },
    { name: "Mondongo", aliases: "tripa, guatita" },
    { name: "Sesos", aliases: "seso" },
    { name: "Tripa gorda", aliases: nil },
    { name: "Rabo de vaca", aliases: "cola de vaca" },
    { name: "Ubre", aliases: nil },
    { name: "Riñones de cordero", aliases: nil },
    { name: "Criadillas", aliases: nil },
    { name: "Librillo", aliases: nil },
    { name: "Bonete", aliases: nil },
  ],

  "Fiambres y embutidos" => [
    { name: "Jamón cocido", aliases: "jamón, york" },
    { name: "Jamón crudo", aliases: "prosciutto" },
    { name: "Salame", aliases: "salame tipo milan, salame picado fino" },
    { name: "Salame tipo milan", aliases: nil },
    { name: "Salame tandilero", aliases: nil },
    { name: "Salamín", aliases: "salamin" },
    { name: "Sopressata", aliases: "sopresata" },
    { name: "Chorizo colorado", aliases: "chorizo español" },
    { name: "Chorizo fresco", aliases: "chorizo de cerdo" },
    { name: "Chorizo criollo", aliases: "chorizo para asar" },
    { name: "Chorizo bombón", aliases: nil },
    { name: "Chorizo de pollo", aliases: nil },
    { name: "Morcilla", aliases: "morcilla criolla" },
    { name: "Morcilla vasca", aliases: nil },
    { name: "Bondiola curada", aliases: "bondiola fiambre" },
    { name: "Longaniza", aliases: nil },
    { name: "Longaniza parrillera", aliases: nil },
    { name: "Leberwurst", aliases: "paté de hígado" },
    { name: "Mortadela", aliases: "mortadella" },
    { name: "Pastrami", aliases: nil },
    { name: "Matambre arrollado", aliases: nil },
    { name: "Paleta cocida", aliases: nil },
    { name: "Lomo canadiense", aliases: nil },
    { name: "Fiambre de pavo", aliases: nil },
    { name: "Fiambre de pollo", aliases: nil },
    { name: "Panceta enrollada", aliases: nil },
    { name: "Coppa", aliases: "copa" },
    { name: "Bresaola", aliases: nil },
    { name: "Carpaccio", aliases: nil },
    { name: "Paté de foie", aliases: "paté" },
    { name: "Picada de fiambres", aliases: nil },
    { name: "Salchicha tipo viena", aliases: "salchicha, panchos" },
    { name: "Salchicha parrillera", aliases: nil },
    { name: "Butifarra", aliases: nil },
    { name: "Kabanos", aliases: nil },
    { name: "Chorizo cantimpalo", aliases: nil },
    { name: "Fuet", aliases: nil },
  ],

  "Cordero y cabrito" => [
    { name: "Cordero entero", aliases: "cordero" },
    { name: "Costillar de cordero", aliases: "rack de cordero" },
    { name: "Paleta de cordero", aliases: nil },
    { name: "Pierna de cordero", aliases: "gigot" },
    { name: "Carré de cordero", aliases: nil },
    { name: "Costilla de cordero", aliases: nil },
    { name: "Cordero patagónico", aliases: nil },
    { name: "Cabrito", aliases: "chivito" },
    { name: "Pierna de cabrito", aliases: nil },
    { name: "Costillar de cabrito", aliases: nil },
    { name: "Guiso de cordero", aliases: nil },
  ],

  "Verduras y hortalizas" => [
    { name: "Papa", aliases: "patata, papa blanca" },
    { name: "Papa negra", aliases: nil },
    { name: "Papa rojas", aliases: "papa colorada" },
    { name: "Papa andina", aliases: nil },
    { name: "Papín", aliases: "papa pequeña" },
    { name: "Batata", aliases: "boniato, camote" },
    { name: "Batata blanca", aliases: nil },
    { name: "Mandioca", aliases: "yuca, casava" },
    { name: "Zapallo", aliases: "zapallo criollo, calabaza" },
    { name: "Zapallo anco", aliases: "anco, butternut" },
    { name: "Zapallo kabutiá", aliases: "kabutia, calabaza japonesa" },
    { name: "Zapallo plomo", aliases: nil },
    { name: "Zapallito verde", aliases: "zapallito, zapallito redondo" },
    { name: "Zapallito largo", aliases: nil },
    { name: "Zucchini", aliases: "calabacín, calabacita" },
    { name: "Tomate redondo", aliases: "tomate, tomate común" },
    { name: "Tomate perita", aliases: "tomate roma" },
    { name: "Tomate cherry", aliases: "tomatito, tomate cereza" },
    { name: "Tomate kumato", aliases: nil },
    { name: "Tomate raf", aliases: nil },
    { name: "Tomate seco", aliases: "tomates secos" },
    { name: "Cebolla blanca", aliases: "cebolla, cebolla común" },
    { name: "Cebolla morada", aliases: "cebolla roja, cebolla colorada" },
    { name: "Cebolla de verdeo", aliases: "verdeo, cebolla larga, cebollín" },
    { name: "Cebollita de verdeo", aliases: nil },
    { name: "Echalote", aliases: "chalota, shallot" },
    { name: "Ajo", aliases: "ajo blanco, diente de ajo" },
    { name: "Ajo morado", aliases: nil },
    { name: "Ajo negro", aliases: nil },
    { name: "Morrón rojo", aliases: "pimiento rojo" },
    { name: "Morrón verde", aliases: "pimiento verde" },
    { name: "Morrón amarillo", aliases: "pimiento amarillo" },
    { name: "Ají vinagre", aliases: "ají rojo en vinagre" },
    { name: "Ají picante", aliases: "ají, chile" },
    { name: "Jalapeño", aliases: nil },
    { name: "Locoto", aliases: "rocoto" },
    { name: "Berenjena", aliases: nil },
    { name: "Berenjena japonesa", aliases: nil },
    { name: "Choclo", aliases: "maíz, elote, mazorca" },
    { name: "Choclo desgranado", aliases: nil },
    { name: "Chaucha", aliases: "ejote, judía verde, poroto verde" },
    { name: "Arveja fresca", aliases: "arvejas, guisante" },
    { name: "Haba fresca", aliases: "habas" },
    { name: "Puerro", aliases: nil },
    { name: "Remolacha", aliases: "beterraga, betabel" },
    { name: "Nabo", aliases: nil },
    { name: "Nabo daikon", aliases: "daikon, rábano japonés" },
    { name: "Rabanito", aliases: "rábano" },
    { name: "Rúcula", aliases: "arúgula" },
    { name: "Espinaca", aliases: nil },
    { name: "Acelga", aliases: nil },
    { name: "Lechuga criolla", aliases: "lechuga" },
    { name: "Lechuga mantecosa", aliases: "lechuga mantecosa, lechuga boston" },
    { name: "Lechuga morada", aliases: nil },
    { name: "Lechuga romana", aliases: nil },
    { name: "Lechuga capuchina", aliases: nil },
    { name: "Radicheta", aliases: "achicoria silvestre" },
    { name: "Radicchio", aliases: "achicoria roja" },
    { name: "Achicoria", aliases: nil },
    { name: "Endivia", aliases: nil },
    { name: "Escarola", aliases: nil },
    { name: "Berro", aliases: nil },
    { name: "Col rizada", aliases: "kale" },
    { name: "Repollo blanco", aliases: "repollo, col blanca" },
    { name: "Repollo morado", aliases: "repollo colorado" },
    { name: "Repollito de Bruselas", aliases: "coles de bruselas" },
    { name: "Coliflor", aliases: nil },
    { name: "Brócoli", aliases: "brocoli, broccoli" },
    { name: "Broccolini", aliases: nil },
    { name: "Hinojo", aliases: "fenouil" },
    { name: "Apio", aliases: "celery" },
    { name: "Espárrago verde", aliases: "espárrago" },
    { name: "Espárrago blanco", aliases: nil },
    { name: "Alcaucil", aliases: "alcachofa, artichoke" },
    { name: "Palmito fresco", aliases: nil },
    { name: "Pepino", aliases: nil },
    { name: "Pepino largo", aliases: "pepino holandés" },
    { name: "Pepino para pickle", aliases: nil },
    { name: "Zanahoria", aliases: nil },
    { name: "Zanahoria baby", aliases: "mini zanahoria" },
    { name: "Hongos champignon", aliases: "champiñón, champignon" },
    { name: "Hongos portobello", aliases: "portobello" },
    { name: "Hongos shiitake", aliases: "shiitake" },
    { name: "Hongos de pino", aliases: nil },
    { name: "Hongos secos", aliases: "hongos deshidratados" },
    { name: "Champiñones en lata", aliases: nil },
    { name: "Choclo baby", aliases: "choclitos" },
    { name: "Pak choi", aliases: "bok choy" },
    { name: "Brote de soja", aliases: "brotes de soja" },
    { name: "Brote de alfalfa", aliases: nil },
    { name: "Jengibre fresco", aliases: "jengibre, kion" },
    { name: "Mandioquita", aliases: nil },
    { name: "Ñame", aliases: nil },
    { name: "Okra", aliases: "quimbombó" },
    { name: "Perejil", aliases: "perejil fresco" },
    { name: "Cilantro fresco", aliases: "cilantro, coriandro" },
    { name: "Albahaca fresca", aliases: "albahaca" },
    { name: "Menta fresca", aliases: "menta, hierbabuena" },
    { name: "Romero fresco", aliases: "romero" },
    { name: "Tomillo fresco", aliases: "tomillo" },
    { name: "Orégano fresco", aliases: nil },
    { name: "Salvia fresca", aliases: "salvia" },
    { name: "Ciboulette fresca", aliases: "ciboulette, cebollino" },
    { name: "Eneldo fresco", aliases: "eneldo, dill" },
    { name: "Estragón fresco", aliases: "estragón" },
    { name: "Cúrcuma fresca", aliases: nil },
  ],

  "Frutas" => [
    { name: "Manzana roja", aliases: "manzana, manzana red delicious" },
    { name: "Manzana verde", aliases: "manzana granny smith" },
    { name: "Manzana gala", aliases: nil },
    { name: "Manzana fuji", aliases: nil },
    { name: "Naranja", aliases: "naranja de jugo" },
    { name: "Naranja de ombligo", aliases: "naranja navel" },
    { name: "Mandarina", aliases: nil },
    { name: "Pomelo", aliases: "toronja" },
    { name: "Pomelo rosado", aliases: nil },
    { name: "Limón", aliases: "limón amarillo" },
    { name: "Lima", aliases: "limón verde" },
    { name: "Banana", aliases: "plátano, guineo" },
    { name: "Banana de la isla", aliases: nil },
    { name: "Frutilla", aliases: "fresa, strawberry" },
    { name: "Frambuesa", aliases: nil },
    { name: "Arándano", aliases: "blueberry" },
    { name: "Mora", aliases: "zarzamora, blackberry" },
    { name: "Grosella", aliases: nil },
    { name: "Durazno", aliases: "melocotón" },
    { name: "Pelón", aliases: "nectarina" },
    { name: "Damasco", aliases: "albaricoque" },
    { name: "Ciruela", aliases: nil },
    { name: "Ciruela roja", aliases: nil },
    { name: "Ciruela pasa", aliases: "ciruelas pasas, ciruela desecada" },
    { name: "Cereza", aliases: nil },
    { name: "Uva negra", aliases: "uva morada" },
    { name: "Uva blanca", aliases: "uva verde" },
    { name: "Uva rosada", aliases: nil },
    { name: "Uva de mesa", aliases: nil },
    { name: "Pasas de uva", aliases: "uvas pasas" },
    { name: "Sandía", aliases: "patilla" },
    { name: "Melón", aliases: nil },
    { name: "Melón rocío de miel", aliases: "honeydew" },
    { name: "Ananá", aliases: "piña, anana" },
    { name: "Kiwi", aliases: nil },
    { name: "Kiwi gold", aliases: nil },
    { name: "Mango", aliases: nil },
    { name: "Palta", aliases: "aguacate, avocado" },
    { name: "Palta hass", aliases: nil },
    { name: "Higo", aliases: "higo fresco" },
    { name: "Higo seco", aliases: "higos secos" },
    { name: "Membrillo", aliases: nil },
    { name: "Granada", aliases: nil },
    { name: "Tuna", aliases: "higo chumbo, prickly pear" },
    { name: "Papaya", aliases: "mamón" },
    { name: "Maracuyá", aliases: "fruta de la pasión, passion fruit" },
    { name: "Guayaba", aliases: nil },
    { name: "Coco fresco", aliases: "coco" },
    { name: "Chirimoya", aliases: nil },
    { name: "Carambola", aliases: "star fruit" },
    { name: "Litchi", aliases: "lichi" },
    { name: "Pera", aliases: nil },
    { name: "Pera williams", aliases: nil },
    { name: "Níspero", aliases: nil },
    { name: "Kumquat", aliases: "quinoto" },
    { name: "Caqui", aliases: nil },
    { name: "Dátil", aliases: "dátiles" },
    { name: "Acerola", aliases: nil },
    { name: "Fruta abrillantada", aliases: "frutas confitadas" },
    { name: "Mix de frutas secas", aliases: "frutas desecadas" },
    { name: "Arándano deshidratado", aliases: nil },
    { name: "Banana deshidratada", aliases: nil },
    { name: "Mango deshidratado", aliases: nil },
    { name: "Ananá en almíbar", aliases: nil },
    { name: "Durazno en almíbar", aliases: "duraznos en lata" },
    { name: "Pera en almíbar", aliases: nil },
    { name: "Cereza en almíbar", aliases: "cerezas al marrasquino" },
    { name: "Cóctel de frutas en almíbar", aliases: "ensalada de frutas en lata" },
    { name: "Limón en conserva", aliases: nil },
  ],

  "Lácteos y huevos" => [
    { name: "Leche entera", aliases: "leche" },
    { name: "Leche descremada", aliases: "leche desnatada" },
    { name: "Leche deslactosada", aliases: "leche sin lactosa" },
    { name: "Leche en polvo", aliases: nil },
    { name: "Leche evaporada", aliases: nil },
    { name: "Leche condensada", aliases: nil },
    { name: "Leche chocolatada", aliases: "chocolatada" },
    { name: "Crema de leche", aliases: "crema, nata" },
    { name: "Crema doble", aliases: "crema extra grasa" },
    { name: "Media crema", aliases: nil },
    { name: "Manteca", aliases: "mantequilla" },
    { name: "Manteca sin sal", aliases: nil },
    { name: "Queso cremoso", aliases: "queso crema" },
    { name: "Queso untable", aliases: "queso blanco" },
    { name: "Queso port salut", aliases: "port salut" },
    { name: "Queso sardo", aliases: nil },
    { name: "Queso provolone", aliases: nil },
    { name: "Queso provoleta", aliases: "provoleta" },
    { name: "Queso parmesano", aliases: "parmigiano reggiano" },
    { name: "Queso reggianito", aliases: "reggianito" },
    { name: "Queso roquefort", aliases: "queso azul" },
    { name: "Queso gruyère", aliases: "gruyere" },
    { name: "Queso fontina", aliases: nil },
    { name: "Queso cheddar", aliases: nil },
    { name: "Queso muzzarella", aliases: "mozzarella, muzza" },
    { name: "Queso muzzarella fresca", aliases: "burrata" },
    { name: "Queso ricota", aliases: "ricotta" },
    { name: "Queso mascarpone", aliases: nil },
    { name: "Queso brie", aliases: nil },
    { name: "Queso camembert", aliases: nil },
    { name: "Queso tybo", aliases: nil },
    { name: "Queso dambo", aliases: nil },
    { name: "Queso pategrás", aliases: nil },
    { name: "Queso gouda", aliases: nil },
    { name: "Queso edam", aliases: nil },
    { name: "Queso emmental", aliases: nil },
    { name: "Queso manchego", aliases: nil },
    { name: "Queso feta", aliases: nil },
    { name: "Queso halloumi", aliases: nil },
    { name: "Queso de cabra", aliases: nil },
    { name: "Queso tandil", aliases: nil },
    { name: "Queso rallado", aliases: "queso de rallar" },
    { name: "Queso en hebras", aliases: nil },
    { name: "Dulce de leche", aliases: "ddl" },
    { name: "Dulce de leche repostero", aliases: "ddl repostero" },
    { name: "Dulce de leche colonial", aliases: nil },
    { name: "Dulce de leche dietético", aliases: nil },
    { name: "Yogur natural", aliases: "yogur" },
    { name: "Yogur griego", aliases: nil },
    { name: "Yogur descremado", aliases: nil },
    { name: "Yogur bebible", aliases: nil },
    { name: "Yogur de frutilla", aliases: nil },
    { name: "Yogur de vainilla", aliases: nil },
    { name: "Huevo de gallina", aliases: "huevo" },
    { name: "Huevo de codorniz", aliases: nil },
    { name: "Clara de huevo", aliases: "claras" },
    { name: "Yema de huevo", aliases: "yemas" },
    { name: "Huevo pasteurizado", aliases: nil },
    { name: "Suero de leche", aliases: "buttermilk" },
    { name: "Queso cottage", aliases: nil },
    { name: "Leche de coco", aliases: nil },
    { name: "Leche de almendras", aliases: nil },
    { name: "Leche de soja", aliases: "leche de soya" },
    { name: "Leche de avena", aliases: nil },
    { name: "Leche de arroz", aliases: nil },
    { name: "Crema vegetal", aliases: nil },
  ],

  "Harinas, cereales y legumbres" => [
    { name: "Harina 000", aliases: "harina triple cero" },
    { name: "Harina 0000", aliases: "harina cuatro cero" },
    { name: "Harina leudante", aliases: nil },
    { name: "Harina integral", aliases: nil },
    { name: "Harina de maíz", aliases: nil },
    { name: "Harina de centeno", aliases: nil },
    { name: "Harina de trigo sarraceno", aliases: "harina de alforfón, harina de trigo negro" },
    { name: "Harina de espelta", aliases: nil },
    { name: "Harina de arroz", aliases: nil },
    { name: "Harina de garbanzos", aliases: nil },
    { name: "Harina de avena", aliases: nil },
    { name: "Harina de almendras", aliases: nil },
    { name: "Harina de coco", aliases: nil },
    { name: "Harina de mandioca", aliases: nil },
    { name: "Fécula de maíz", aliases: "maicena, almidón de maíz" },
    { name: "Almidón de mandioca", aliases: "tapioca, fécula de mandioca" },
    { name: "Fécula de papa", aliases: nil },
    { name: "Polenta", aliases: "polenta instantánea, harina de maíz para polenta" },
    { name: "Polenta presto pronta", aliases: nil },
    { name: "Sémola de trigo", aliases: "semolín" },
    { name: "Avena arrollada", aliases: "avena, copos de avena" },
    { name: "Avena instantánea", aliases: nil },
    { name: "Salvado de trigo", aliases: nil },
    { name: "Salvado de avena", aliases: nil },
    { name: "Germen de trigo", aliases: nil },
    { name: "Arroz blanco", aliases: "arroz, arroz largo fino" },
    { name: "Arroz doble carolina", aliases: "arroz carolina" },
    { name: "Arroz integral", aliases: nil },
    { name: "Arroz basmati", aliases: nil },
    { name: "Arroz yamaní", aliases: "arroz yamani" },
    { name: "Arroz arborio", aliases: "arroz para risotto" },
    { name: "Arroz parboil", aliases: "arroz parbolizado" },
    { name: "Arroz japonés", aliases: "arroz para sushi" },
    { name: "Arroz negro", aliases: nil },
    { name: "Arroz salvaje", aliases: nil },
    { name: "Trigo burgol", aliases: "trigo partido, bulgur" },
    { name: "Trigo candeal", aliases: nil },
    { name: "Cebada perlada", aliases: "cebada, cebada perla" },
    { name: "Quinoa blanca", aliases: "quinoa, quinua" },
    { name: "Quinoa roja", aliases: nil },
    { name: "Quinoa negra", aliases: nil },
    { name: "Mijo", aliases: nil },
    { name: "Amaranto", aliases: nil },
    { name: "Cuscús", aliases: "cous cous" },
    { name: "Lentejas", aliases: "lenteja" },
    { name: "Lentejas rojas", aliases: "lentejas turcas" },
    { name: "Porotos negros", aliases: "frijoles negros" },
    { name: "Porotos colorados", aliases: "frijoles rojos, kidney beans" },
    { name: "Porotos alubia", aliases: "porotos blancos, alubias" },
    { name: "Porotos pallares", aliases: "pallares" },
    { name: "Porotos manteca", aliases: "lima beans" },
    { name: "Porotos de soja", aliases: "soja en grano" },
    { name: "Porotos aduki", aliases: "azuki" },
    { name: "Porotos mung", aliases: nil },
    { name: "Garbanzos", aliases: "garbanzo" },
    { name: "Arvejas secas", aliases: "arvejas partidas" },
    { name: "Habas secas", aliases: nil },
    { name: "Chía", aliases: "semillas de chía" },
    { name: "Lino", aliases: "linaza, semillas de lino" },
    { name: "Cereales de desayuno", aliases: nil },
    { name: "Granola", aliases: nil },
    { name: "Muesli", aliases: nil },
    { name: "Copos de maíz", aliases: "cornflakes" },
    { name: "Pan rallado", aliases: "pan molido" },
    { name: "Pan rallado saborizado", aliases: nil },
    { name: "Rebozador", aliases: nil },
    { name: "Premezcla para celíacos", aliases: "premezcla sin gluten, premezcla sin TACC" },
  ],

  "Condimentos y especias" => [
    { name: "Sal fina", aliases: "sal, sal de mesa" },
    { name: "Sal gruesa", aliases: "sal parrillera" },
    { name: "Sal marina", aliases: nil },
    { name: "Sal rosada del Himalaya", aliases: nil },
    { name: "Flor de sal", aliases: nil },
    { name: "Pimienta negra", aliases: "pimienta en grano" },
    { name: "Pimienta negra molida", aliases: "pimienta" },
    { name: "Pimienta blanca", aliases: nil },
    { name: "Pimienta de Jamaica", aliases: nil },
    { name: "Pimienta rosa", aliases: nil },
    { name: "Pimienta de cayena", aliases: "cayena, cayenne" },
    { name: "Mix de pimientas", aliases: nil },
    { name: "Pimentón dulce", aliases: "pimentón" },
    { name: "Pimentón picante", aliases: nil },
    { name: "Pimentón ahumado", aliases: "pimentón de la vera" },
    { name: "Orégano seco", aliases: "orégano" },
    { name: "Ají molido", aliases: "ají triturado, red pepper flakes" },
    { name: "Chimichurri seco", aliases: "chimichurri en sobre" },
    { name: "Comino", aliases: "comino en polvo" },
    { name: "Comino en grano", aliases: nil },
    { name: "Nuez moscada", aliases: nil },
    { name: "Canela en polvo", aliases: "canela" },
    { name: "Canela en rama", aliases: nil },
    { name: "Clavo de olor", aliases: nil },
    { name: "Cúrcuma en polvo", aliases: "cúrcuma" },
    { name: "Curry en polvo", aliases: "curry" },
    { name: "Jengibre en polvo", aliases: nil },
    { name: "Laurel", aliases: "hoja de laurel" },
    { name: "Tomillo seco", aliases: nil },
    { name: "Romero seco", aliases: nil },
    { name: "Albahaca seca", aliases: nil },
    { name: "Salvia seca", aliases: nil },
    { name: "Estragón seco", aliases: nil },
    { name: "Eneldo seco", aliases: nil },
    { name: "Provenzal", aliases: "ajo y perejil deshidratados" },
    { name: "Hierbas provenzales", aliases: "herbes de provence" },
    { name: "Azafrán", aliases: nil },
    { name: "Merkén", aliases: "merken, merquén" },
    { name: "Cardamomo", aliases: nil },
    { name: "Anís estrellado", aliases: "badián" },
    { name: "Semillas de anís", aliases: "anís en grano" },
    { name: "Semillas de hinojo", aliases: nil },
    { name: "Semillas de mostaza", aliases: nil },
    { name: "Semillas de cilantro", aliases: "coriandro en grano" },
    { name: "Semillas de amapola", aliases: nil },
    { name: "Fenogreco", aliases: nil },
    { name: "Garam masala", aliases: nil },
    { name: "Ras el hanout", aliases: nil },
    { name: "Cinco especias chinas", aliases: nil },
    { name: "Tandoori", aliases: "masala tandoori" },
    { name: "Wasabi", aliases: nil },
    { name: "Caldo de carne en cubos", aliases: "cubito de caldo, caldo Knorr" },
    { name: "Caldo de pollo en cubos", aliases: nil },
    { name: "Caldo de verduras en cubos", aliases: nil },
    { name: "Caldo concentrado", aliases: nil },
    { name: "Saborizador en polvo", aliases: nil },
    { name: "Glutamato monosódico", aliases: "ajinomoto, umami" },
    { name: "Páprika", aliases: "paprika" },
    { name: "Ajo en polvo", aliases: nil },
    { name: "Cebolla en polvo", aliases: nil },
    { name: "Extracto de carne", aliases: nil },
    { name: "Adobo para carne", aliases: nil },
    { name: "Condimento para arroz", aliases: nil },
    { name: "Condimento para pizza", aliases: nil },
    { name: "Chimichurri preparado", aliases: "chimichurri" },
    { name: "Mostaza en grano", aliases: nil },
    { name: "Pimienta de Sichuan", aliases: nil },
    { name: "Chile ancho seco", aliases: nil },
    { name: "Chile chipotle", aliases: "chipotle" },
    { name: "Pasta de ají", aliases: nil },
    { name: "Sumac", aliases: nil },
    { name: "Za'atar", aliases: "zaatar" },
  ],

  "Salsas y aderezos" => [
    { name: "Salsa de tomate", aliases: "passata, puré de tomate" },
    { name: "Extracto de tomate", aliases: "concentrado de tomate, doble concentrado" },
    { name: "Ketchup", aliases: "catsup" },
    { name: "Mostaza", aliases: "mostaza amarilla" },
    { name: "Mostaza Dijon", aliases: nil },
    { name: "Mostaza a la antigua", aliases: "mostaza en grano" },
    { name: "Mayonesa", aliases: "mayo" },
    { name: "Mayonesa light", aliases: nil },
    { name: "Salsa golf", aliases: nil },
    { name: "Salsa criolla", aliases: nil },
    { name: "Salsa chimichurri", aliases: nil },
    { name: "Vinagreta", aliases: nil },
    { name: "Salsa de soja", aliases: "soja, soy sauce" },
    { name: "Salsa de soja light", aliases: nil },
    { name: "Salsa inglesa", aliases: "salsa Worcestershire, Lea & Perrins" },
    { name: "Tabasco", aliases: "salsa tabasco" },
    { name: "Sriracha", aliases: nil },
    { name: "Salsa picante", aliases: nil },
    { name: "Salsa de ostras", aliases: "oyster sauce" },
    { name: "Salsa de pescado", aliases: "fish sauce, nam pla" },
    { name: "Salsa teriyaki", aliases: nil },
    { name: "Salsa BBQ", aliases: "salsa barbacoa" },
    { name: "Salsa HP", aliases: nil },
    { name: "Salsa de arándanos", aliases: nil },
    { name: "Pesto genovés", aliases: "pesto" },
    { name: "Salsa fileto", aliases: "salsa pomodoro" },
    { name: "Salsa bolognesa", aliases: "salsa boloñesa" },
    { name: "Salsa blanca", aliases: "bechamel, béchamel" },
    { name: "Salsa rosa", aliases: nil },
    { name: "Salsa tártara", aliases: nil },
    { name: "Tahini", aliases: "tahina, pasta de sésamo" },
    { name: "Hummus", aliases: nil },
    { name: "Guacamole", aliases: nil },
    { name: "Harissa", aliases: nil },
    { name: "Miso", aliases: "pasta de miso" },
    { name: "Chutney de mango", aliases: nil },
    { name: "Salsa agridulce", aliases: nil },
    { name: "Salsa cesar", aliases: nil },
    { name: "Pasta de curry", aliases: nil },
    { name: "Sambal oelek", aliases: nil },
    { name: "Gochujang", aliases: nil },
    { name: "Hoisin", aliases: "salsa hoisin" },
    { name: "Aderezo ranch", aliases: nil },
  ],

  "Aceites y vinagres" => [
    { name: "Aceite de girasol", aliases: "aceite" },
    { name: "Aceite de oliva", aliases: nil },
    { name: "Aceite de oliva extra virgen", aliases: "AOVE" },
    { name: "Aceite de maíz", aliases: nil },
    { name: "Aceite de coco", aliases: nil },
    { name: "Aceite de sésamo", aliases: "aceite de ajonjolí" },
    { name: "Aceite de palta", aliases: "aceite de aguacate" },
    { name: "Aceite de canola", aliases: nil },
    { name: "Aceite de uva", aliases: nil },
    { name: "Aceite de nuez", aliases: nil },
    { name: "Aceite de trufa", aliases: nil },
    { name: "Aceite en spray", aliases: "rocío vegetal" },
    { name: "Vinagre de alcohol", aliases: "vinagre blanco, vinagre común" },
    { name: "Vinagre de manzana", aliases: nil },
    { name: "Vinagre de vino tinto", aliases: nil },
    { name: "Vinagre de vino blanco", aliases: nil },
    { name: "Vinagre balsámico", aliases: "aceto balsámico" },
    { name: "Vinagre de jerez", aliases: nil },
    { name: "Vinagre de arroz", aliases: nil },
    { name: "Crema de aceto", aliases: "reducción balsámica" },
    { name: "Jugo de limón", aliases: nil },
  ],

  "Azúcares y endulzantes" => [
    { name: "Azúcar común", aliases: "azúcar blanca, azúcar granulada" },
    { name: "Azúcar impalpable", aliases: "azúcar glass, azúcar en polvo" },
    { name: "Azúcar negra", aliases: "azúcar morena" },
    { name: "Azúcar rubia", aliases: "azúcar demerara" },
    { name: "Azúcar mascabo", aliases: "azúcar muscovado" },
    { name: "Azúcar orgánica", aliases: nil },
    { name: "Miel", aliases: "miel de abejas" },
    { name: "Miel de caña", aliases: nil },
    { name: "Stevia", aliases: nil },
    { name: "Edulcorante líquido", aliases: "edulcorante" },
    { name: "Edulcorante en polvo", aliases: nil },
    { name: "Jarabe de maíz", aliases: "corn syrup" },
    { name: "Jarabe de arce", aliases: "maple syrup" },
    { name: "Melaza", aliases: "miel de caña" },
    { name: "Jarabe de agave", aliases: nil },
    { name: "Glucosa", aliases: "jarabe de glucosa" },
    { name: "Azúcar invertida", aliases: "trimoline" },
    { name: "Caramelo líquido", aliases: nil },
    { name: "Panela", aliases: "rapadura" },
  ],

  "Bebidas para cocinar" => [
    { name: "Vino tinto", aliases: nil },
    { name: "Vino blanco", aliases: nil },
    { name: "Vino marsala", aliases: "marsala" },
    { name: "Oporto", aliases: "vino oporto, port wine" },
    { name: "Jerez", aliases: "sherry" },
    { name: "Coñac", aliases: "cognac" },
    { name: "Ron", aliases: nil },
    { name: "Grapa", aliases: "grappa" },
    { name: "Brandy", aliases: nil },
    { name: "Whisky", aliases: nil },
    { name: "Vodka", aliases: nil },
    { name: "Cerveza rubia", aliases: "cerveza" },
    { name: "Cerveza negra", aliases: nil },
    { name: "Cerveza de trigo", aliases: nil },
    { name: "Sidra", aliases: nil },
    { name: "Champagne", aliases: "espumante" },
    { name: "Vermú", aliases: "vermouth" },
    { name: "Amaretto", aliases: nil },
    { name: "Grand Marnier", aliases: nil },
    { name: "Kirsch", aliases: nil },
    { name: "Licor de café", aliases: nil },
    { name: "Licor de chocolate", aliases: nil },
    { name: "Licor de menta", aliases: nil },
    { name: "Limoncello", aliases: nil },
    { name: "Anís", aliases: nil },
    { name: "Agua", aliases: "agua potable" },
    { name: "Agua con gas", aliases: "soda" },
    { name: "Café", aliases: "café molido" },
    { name: "Café instantáneo", aliases: "nescafé" },
    { name: "Café espresso", aliases: nil },
    { name: "Té negro", aliases: "té" },
    { name: "Té verde", aliases: nil },
    { name: "Yerba mate", aliases: "yerba" },
    { name: "Mate cocido", aliases: nil },
    { name: "Cacao en polvo", aliases: "cacao" },
  ],

  "Chocolate y cacao" => [
    { name: "Cacao amargo en polvo", aliases: "cacao amargo" },
    { name: "Chocolate semiamargo", aliases: "chocolate negro" },
    { name: "Chocolate con leche", aliases: nil },
    { name: "Chocolate blanco", aliases: nil },
    { name: "Chocolate amargo 70%", aliases: nil },
    { name: "Chocolate amargo 85%", aliases: nil },
    { name: "Cobertura de chocolate", aliases: "chocolate cobertura" },
    { name: "Baño de repostería semiamargo", aliases: nil },
    { name: "Baño de repostería con leche", aliases: nil },
    { name: "Baño de repostería blanco", aliases: nil },
    { name: "Chips de chocolate", aliases: "gotitas de chocolate, chispas de chocolate" },
    { name: "Chips de chocolate blanco", aliases: nil },
    { name: "Chocolate taza", aliases: nil },
    { name: "Cacao para chocolatada", aliases: "Nesquik, Toddy" },
    { name: "Nutella", aliases: "crema de avellanas, pasta de avellanas" },
    { name: "Ganache", aliases: nil },
    { name: "Manteca de cacao", aliases: nil },
    { name: "Licor de cacao", aliases: nil },
  ],

  "Frutos secos y semillas" => [
    { name: "Nuez", aliases: "nuez de nogal, nueces" },
    { name: "Nuez pelada", aliases: nil },
    { name: "Nuez pecán", aliases: "pecan" },
    { name: "Almendra", aliases: "almendras" },
    { name: "Almendra pelada", aliases: nil },
    { name: "Almendra fileteada", aliases: "almendras laminadas" },
    { name: "Almendra molida", aliases: "almendras procesadas" },
    { name: "Maní", aliases: "cacahuate, cacahuete" },
    { name: "Maní tostado", aliases: "maní salado" },
    { name: "Maní con cáscara", aliases: nil },
    { name: "Manteca de maní", aliases: "mantequilla de maní, peanut butter" },
    { name: "Avellana", aliases: "avellanas" },
    { name: "Castaña de cajú", aliases: "anacardo, cashew, cajú" },
    { name: "Pistacho", aliases: "pistachos" },
    { name: "Piñón", aliases: "piñones" },
    { name: "Castaña", aliases: "castañas" },
    { name: "Nuez de macadamia", aliases: "macadamia" },
    { name: "Nuez de Brasil", aliases: nil },
    { name: "Semillas de girasol", aliases: "pipas" },
    { name: "Semillas de chía", aliases: "chía" },
    { name: "Semillas de lino", aliases: "linaza" },
    { name: "Semillas de sésamo", aliases: "ajonjolí" },
    { name: "Semillas de sésamo negro", aliases: nil },
    { name: "Semillas de zapallo", aliases: "pepitas" },
    { name: "Semillas de amapola", aliases: nil },
    { name: "Coco rallado", aliases: nil },
    { name: "Coco deshidratado", aliases: nil },
    { name: "Mix de frutos secos", aliases: "mix energético" },
    { name: "Pasta de almendras", aliases: "mazapán" },
    { name: "Praline", aliases: "praliné" },
  ],

  "Conservas y enlatados" => [
    { name: "Tomate triturado", aliases: "tomate triturado en lata" },
    { name: "Tomate perita en lata", aliases: "tomates pelados" },
    { name: "Tomate cubeteado en lata", aliases: "tomate en cubos" },
    { name: "Puré de tomate", aliases: "passata" },
    { name: "Choclo en lata", aliases: "choclo en grano, maíz en lata" },
    { name: "Choclo cremoso en lata", aliases: nil },
    { name: "Arvejas en lata", aliases: nil },
    { name: "Porotos en lata", aliases: nil },
    { name: "Garbanzos en lata", aliases: nil },
    { name: "Lentejas en lata", aliases: nil },
    { name: "Atún en aceite", aliases: nil },
    { name: "Atún al natural", aliases: nil },
    { name: "Sardinas en aceite", aliases: nil },
    { name: "Caballa en aceite", aliases: nil },
    { name: "Aceitunas verdes", aliases: "aceituna verde" },
    { name: "Aceitunas negras", aliases: "aceituna negra" },
    { name: "Aceitunas rellenas", aliases: nil },
    { name: "Aceitunas descarozadas", aliases: nil },
    { name: "Palmitos en conserva", aliases: "palmitos" },
    { name: "Morrones en conserva", aliases: "pimientos asados" },
    { name: "Pickles", aliases: "pepinillos en vinagre" },
    { name: "Alcaparras", aliases: nil },
    { name: "Anchoas en aceite", aliases: nil },
    { name: "Pasta de aceitunas", aliases: "olivada, tapenade" },
    { name: "Tomates secos en aceite", aliases: nil },
    { name: "Pimientos del piquillo", aliases: nil },
    { name: "Berenjenas en escabeche", aliases: nil },
    { name: "Chucrut", aliases: nil },
    { name: "Choclo baby en lata", aliases: nil },
    { name: "Corazones de alcaucil en lata", aliases: nil },
    { name: "Espárragos en conserva", aliases: nil },
    { name: "Jardinera en lata", aliases: nil },
    { name: "Brotes de bambú", aliases: nil },
    { name: "Castañas de agua", aliases: nil },
    { name: "Leche de coco en lata", aliases: nil },
  ],

  "Panificados y masas" => [
    { name: "Pan francés", aliases: "pan flauta, flautita" },
    { name: "Pan lactal", aliases: "pan de molde" },
    { name: "Pan lactal integral", aliases: nil },
    { name: "Pan de campo", aliases: "pan casero" },
    { name: "Pan árabe", aliases: "pan pita" },
    { name: "Pan ciabatta", aliases: nil },
    { name: "Pan focaccia", aliases: nil },
    { name: "Pan de centeno", aliases: nil },
    { name: "Pan baguette", aliases: nil },
    { name: "Pan negro", aliases: "pan pumpernickel" },
    { name: "Pan de hamburguesa", aliases: nil },
    { name: "Pan de pancho", aliases: "pan de hot dog" },
    { name: "Pan rallado", aliases: "pan molido, miga de pan" },
    { name: "Pan rallado saborizado", aliases: nil },
    { name: "Panko", aliases: nil },
    { name: "Galletitas de agua", aliases: "crackers" },
    { name: "Galletitas saladas", aliases: nil },
    { name: "Galletitas dulces", aliases: nil },
    { name: "Grisines", aliases: "grisín" },
    { name: "Tostadas", aliases: "tostadas de pan" },
    { name: "Tapas de empanada para horno", aliases: nil },
    { name: "Tapas de empanada para freír", aliases: "tapas criollas" },
    { name: "Tapas de tarta", aliases: nil },
    { name: "Masa de hojaldre", aliases: "hojaldre" },
    { name: "Masa philo", aliases: "masa filo" },
    { name: "Masa brick", aliases: nil },
    { name: "Prepizza", aliases: "masa de pizza" },
    { name: "Tapas de pasqualina", aliases: nil },
    { name: "Tortillas de trigo", aliases: "wraps" },
    { name: "Tortillas de maíz", aliases: nil },
    { name: "Pionono", aliases: "brazo gitano, plancha de pionono" },
    { name: "Vainillas", aliases: "bizcocho vainilla" },
    { name: "Bizcochuelo", aliases: nil },
    { name: "Medialunas", aliases: nil },
    { name: "Facturas", aliases: nil },
    { name: "Croissant", aliases: nil },
    { name: "Ñoquis frescos", aliases: "ñoquis" },
    { name: "Discos de masa para wantón", aliases: "masa wantón" },
  ],

  "Pastas secas" => [
    { name: "Fideos spaghetti", aliases: "espaguetis, spaghetti" },
    { name: "Fideos tallarines", aliases: "tallarines, fettuccine, tagliatelle" },
    { name: "Fideos tirabuzón", aliases: "fusilli, tirabuzones" },
    { name: "Fideos mostachol", aliases: "penne, mostaccioli" },
    { name: "Fideos moñito", aliases: "farfalle, moñitos" },
    { name: "Fideos codito", aliases: "macarrones, codo" },
    { name: "Fideos dedalito", aliases: "ditalini, dedal" },
    { name: "Fideos munición", aliases: "pastina" },
    { name: "Fideos cabello de ángel", aliases: "capellini, angel hair" },
    { name: "Fideos vermicelli", aliases: nil },
    { name: "Fideos linguini", aliases: "linguine" },
    { name: "Fideos bucatini", aliases: nil },
    { name: "Fideos rigatoni", aliases: nil },
    { name: "Fideos pappardelle", aliases: nil },
    { name: "Fideos orzo", aliases: "risoni" },
    { name: "Fideos nido", aliases: nil },
    { name: "Fideos guiseros", aliases: "fideos para guiso" },
    { name: "Fideos letras", aliases: nil },
    { name: "Fideos soperos", aliases: nil },
    { name: "Lasaña", aliases: "placas de lasaña" },
    { name: "Canelones", aliases: "placas de canelones" },
    { name: "Ravioles frescos", aliases: "ravioles" },
    { name: "Sorrentinos frescos", aliases: "sorrentinos" },
    { name: "Capelettini", aliases: "capelletti" },
    { name: "Tortellini", aliases: nil },
    { name: "Ñoquis de papa", aliases: "ñoquis" },
    { name: "Fideos de arroz", aliases: nil },
    { name: "Fideos udon", aliases: nil },
    { name: "Fideos soba", aliases: nil },
    { name: "Fideos de huevo", aliases: nil },
    { name: "Fideos integrales", aliases: nil },
    { name: "Fideos sin TACC", aliases: "fideos sin gluten" },
    { name: "Masa para fideos frescos", aliases: nil },
  ],

  "Productos regionales argentinos" => [
    { name: "Dulce de membrillo", aliases: nil },
    { name: "Dulce de batata", aliases: nil },
    { name: "Alfajor de maicena", aliases: nil },
    { name: "Alfajor de chocolate", aliases: nil },
    { name: "Arrope de tuna", aliases: nil },
    { name: "Arrope de chañar", aliases: nil },
    { name: "Algarroba", aliases: "harina de algarroba" },
    { name: "Charqui", aliases: "charque, carne seca" },
    { name: "Quesillo", aliases: "quesillo de cabra" },
    { name: "Empanada tucumana", aliases: nil },
    { name: "Locro", aliases: "base para locro" },
    { name: "Mazamorra", aliases: nil },
    { name: "Maíz pisado", aliases: "mote" },
    { name: "Patay", aliases: nil },
    { name: "Llajua", aliases: nil },
    { name: "Salsa huancaína", aliases: nil },
    { name: "Cayote", aliases: "alcayota" },
    { name: "Dulce de cayote", aliases: "dulce de alcayota" },
    { name: "Dulce de zapallo", aliases: nil },
    { name: "Dulce de higo", aliases: nil },
    { name: "Dulce de ciruela", aliases: nil },
    { name: "Dulce de naranja", aliases: nil },
    { name: "Dulce de frutilla", aliases: "mermelada de frutilla" },
    { name: "Dulce de durazno", aliases: "mermelada de durazno" },
    { name: "Dulce de arándanos", aliases: nil },
    { name: "Dulce de frambuesa", aliases: nil },
    { name: "Dulce de rosa mosqueta", aliases: nil },
    { name: "Dulce de calafate", aliases: nil },
    { name: "Dulce de saúco", aliases: nil },
    { name: "Mermelada de damasco", aliases: nil },
    { name: "Mate cocido en saquitos", aliases: nil },
    { name: "Té de boldo", aliases: nil },
    { name: "Té de cedrón", aliases: nil },
    { name: "Té de manzanilla", aliases: nil },
    { name: "Té de tilo", aliases: nil },
    { name: "Peperina", aliases: nil },
    { name: "Muña muña", aliases: nil },
    { name: "Piquillín", aliases: nil },
    { name: "Maíz pisingallo", aliases: "pochoclo, palomitas de maíz" },
    { name: "Maíz blanco", aliases: "maíz para humita" },
    { name: "Frangollo", aliases: nil },
  ],

  "Levaduras y leudantes" => [
    { name: "Levadura fresca", aliases: "levadura de cerveza" },
    { name: "Levadura seca", aliases: "levadura instantánea, levadura seca activa" },
    { name: "Polvo de hornear", aliases: "polvo leudante, Royal" },
    { name: "Bicarbonato de sodio", aliases: "bicarbonato" },
    { name: "Cremor tártaro", aliases: nil },
    { name: "Masa madre", aliases: "sourdough starter" },
    { name: "Levadura nutricional", aliases: nil },
  ],

  "Extractos y esencias" => [
    { name: "Esencia de vainilla", aliases: "vainilla" },
    { name: "Chaucha de vainilla", aliases: "vaina de vainilla, vanilla bean" },
    { name: "Extracto de almendras", aliases: nil },
    { name: "Ralladura de limón", aliases: nil },
    { name: "Ralladura de naranja", aliases: nil },
    { name: "Agua de rosas", aliases: nil },
    { name: "Agua de azahar", aliases: nil },
    { name: "Esencia de menta", aliases: nil },
    { name: "Esencia de coco", aliases: nil },
    { name: "Esencia de ron", aliases: nil },
    { name: "Esencia de banana", aliases: nil },
    { name: "Pasta de vainilla", aliases: nil },
    { name: "Colorante vegetal rojo", aliases: nil },
    { name: "Colorante vegetal amarillo", aliases: nil },
    { name: "Colorante vegetal azul", aliases: nil },
    { name: "Colorante vegetal verde", aliases: nil },
  ],

  "Gelatinas, espesantes y gelificantes" => [
    { name: "Gelatina sin sabor", aliases: "gelatina en polvo" },
    { name: "Gelatina en láminas", aliases: "colapez, hojas de gelatina" },
    { name: "Gelatina de frutilla", aliases: nil },
    { name: "Gelatina de limón", aliases: nil },
    { name: "Gelatina de naranja", aliases: nil },
    { name: "Gelatina de frambuesa", aliases: nil },
    { name: "Gelatina light", aliases: nil },
    { name: "Agar agar", aliases: nil },
    { name: "Goma xántica", aliases: "xanthan, xantana" },
    { name: "Goma guar", aliases: nil },
    { name: "Pectina", aliases: nil },
    { name: "Carragenina", aliases: nil },
  ],

  "Repostería y decoración" => [
    { name: "Fondant", aliases: "pasta de azúcar" },
    { name: "Pastillaje", aliases: nil },
    { name: "Glasé real", aliases: nil },
    { name: "Granas de colores", aliases: "sprinkles, confites" },
    { name: "Perlas de azúcar", aliases: nil },
    { name: "Obleas", aliases: nil },
    { name: "Merengues", aliases: nil },
    { name: "Papel de arroz", aliases: nil },
    { name: "Oro comestible", aliases: nil },
    { name: "Mousse de chocolate en polvo", aliases: nil },
    { name: "Flan en polvo", aliases: nil },
    { name: "Postre de chocolate en polvo", aliases: nil },
    { name: "Preparado para torta", aliases: "premezcla para torta, cake mix" },
    { name: "Preparado para brownies", aliases: nil },
    { name: "Preparado para muffins", aliases: nil },
    { name: "Crema pastelera en polvo", aliases: nil },
    { name: "Chantilly en polvo", aliases: nil },
    { name: "Crema chantilly", aliases: "crema batida" },
    { name: "Merengue italiano", aliases: nil },
    { name: "Merengue suizo", aliases: nil },
    { name: "Glasé", aliases: nil },
    { name: "Galletitas molidas", aliases: "base de cheesecake" },
    { name: "Dulce de leche en barra", aliases: nil },
    { name: "Crocante de maní", aliases: nil },
  ],

  "Tofu, seitán y proteínas vegetales" => [
    { name: "Tofu firme", aliases: "tofu" },
    { name: "Tofu sedoso", aliases: "silken tofu" },
    { name: "Seitán", aliases: nil },
    { name: "Proteína de soja texturizada", aliases: "soja texturizada, carne de soja" },
    { name: "Tempeh", aliases: nil },
    { name: "Hamburguesa vegetal", aliases: nil },
    { name: "Milanesa de soja", aliases: nil },
    { name: "Salchicha vegana", aliases: nil },
    { name: "Edamame", aliases: nil },
  ],

  "Algas y productos asiáticos" => [
    { name: "Alga nori", aliases: "nori" },
    { name: "Alga kombu", aliases: "kombu" },
    { name: "Alga wakame", aliases: "wakame" },
    { name: "Arroz para sushi", aliases: nil },
    { name: "Vinagre de arroz", aliases: "vinagre para sushi" },
    { name: "Jengibre encurtido", aliases: "gari" },
    { name: "Pasta de wasabi", aliases: nil },
    { name: "Togarashi", aliases: "shichimi" },
    { name: "Salsa tonkatsu", aliases: nil },
    { name: "Dashi", aliases: "caldo dashi" },
    { name: "Mirin", aliases: nil },
    { name: "Sake", aliases: nil },
    { name: "Wonton", aliases: "tapas de wonton" },
    { name: "Harina de tempura", aliases: nil },
    { name: "Leche de coco (lata)", aliases: nil },
    { name: "Curry rojo tailandés", aliases: nil },
    { name: "Curry verde tailandés", aliases: nil },
    { name: "Salsa pad thai", aliases: nil },
    { name: "Aceite de sésamo tostado", aliases: nil },
    { name: "Maní japonés", aliases: nil },
    { name: "Chips de nori", aliases: nil },
  ],

  "Varios y misceláneos" => [
    { name: "Grasa vacuna", aliases: "grasa de vaca, sebo" },
    { name: "Grasa de cerdo refinada", aliases: nil },
    { name: "Aceite usado reciclado", aliases: nil },
    { name: "Hielo", aliases: nil },
    { name: "Papel aluminio", aliases: nil },
    { name: "Film transparente", aliases: nil },
    { name: "Hilo de cocina", aliases: nil },
    { name: "Escarbadientes", aliases: nil },
    { name: "Jugo de naranja", aliases: nil },
    { name: "Jugo de pomelo", aliases: nil },
    { name: "Jugo de manzana", aliases: nil },
    { name: "Jugo de arándanos", aliases: nil },
    { name: "Leche de coco en brick", aliases: nil },
    { name: "Crema de coco", aliases: nil },
    { name: "Agua de coco", aliases: nil },
    { name: "Caldo de huesos", aliases: "bone broth" },
    { name: "Caldo casero de pollo", aliases: nil },
    { name: "Caldo casero de carne", aliases: nil },
    { name: "Caldo casero de verduras", aliases: nil },
    { name: "Fumet de pescado", aliases: "caldo de pescado" },
  ],
}

count = 0
INGREDIENTS.each do |category, items|
  items.each do |item|
    Ingredient.find_or_create_by!(name: item[:name]) do |i|
      i.category = category
      i.aliases = item[:aliases]
    end
    count += 1
  end
end

puts "Se cargaron #{count} ingredientes."
